### ISSUE TITLE
THIS IS NOT HIS CODE

### ISSUE THREAD

**Issue by blaise69** [callbacc/Donut#1]
This user is a whole scammer and shall never be worked with and never share code with him! He gave me a vps just so steal my code and fuck me over because he did not get a Discord Developer Badge also fucked over the developer of Aspire for the same reason this user can and shall never be trusted! If you use this i think u shall think twice, not only will callbacc be charged with copyright but any who uses it as well as for the license is a complete copyright license as well as Fishy and Aspire (licenses are listed below), Also if you are not over 16 of your parent will more than likely be charged with it 

 > These are Donut and Fishys license
```
/* Copyright (C) Blaise  - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * No code shall be shared AT ALL
 */
```
> Aspire
```
/* Copyright (C) Blaise Harrington - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * No code shall be shared AT ALL
 */
```

SO THINK BEFORE YOU DOING SOMETHING

**The original copyright owners for Donut and Fishy are Donut Development And Blaise Harrington | Aspire copyright holders are Aspire Development**

**Comment by callbacc** [comment]
Please prove that this is your code.

**Comment by milanmdev** [comment]
Are you an idiot @callbacc?? You know this is our code and you joined the team just to steal it. Your should be ashamed of this.

**Comment by milanmdev** [comment]
We have much proof that we own this. This was very childish on your end. Already have reported your to GH etc.

**Comment by callbacc** [comment]
Who are you again?

**Comment by milanmdev** [comment]
Shut up right now NVMe. You know who I am, mdev01#0001, and stop playing like this is a big game. You are gonna be charged with lots of fines so you better get some money and explanations ready.

**Comment by milanmdev** [comment]
Also includes getting banned possibly from GH

**Comment by callbacc** [comment]
Could you please tell me who you are?

**Comment by callbacc** [comment]
Open this thread when you got the proof.

**Comment by milanmdev** [comment]
Stop

**Comment by blaise69** [comment]
You want proof i own the mongodb cluster in the .env and that is/was my bot token and my discord ig is in the config, and because all of the commands are the exact same as my code on my private github i have ss of you saying u have my code and were going to post if because u cant get ur developer badge or because i worked with @MrCrypticXDev, You have even told me that if i didnt get @MrCrypticXDev to say sorry to you that you were going to leak my 2 bots code! You are 15 years old start fucking acting like it! I was nothing but fucking nice to you, i let you join my developer team and you legit screw me over like this! If you do not take this code down Legal action will be brought upon you even tho you 15 you commited a legal crime! So please grow a pair of balls and face that ur nothing the badge.
 hiss hiss hiss you little snake!

**Comment by blaise69** [comment]
Keep coming at me i got all sorts of comment

**Comment by milanmdev** [comment]
@callbacc You have no right to do this. Not your code, never will be.

**Comment by milanmdev** [comment]
So I reccoment you shut up, and get some sentences ready to speak to GH and the court.

**Comment by callbacc** [comment]
Can I know who am I talking to?

**Comment by milanmdev** [comment]
Stop. Im legit talking to you in discord rn.

**Comment by callbacc** [comment]
I don't have a discord?

**Comment by milanmdev** [comment]
Bruhhhhhh. Your gh is linked to your discord. Don't play dumb

**Comment by milanmdev** [comment]
![image](https://user-images.githubusercontent.com/29466935/90984128-bb358e80-e538-11ea-81fb-b87f09bb6496.png)
Explain that

**Comment by callbacc** [comment]
Who's that?

**Comment by milanmdev** [comment]
Stop. You know who you are

**Comment by milanmdev** [comment]
You had this in your status

**Comment by milanmdev** [comment]
So stop

**Comment by callbacc** [comment]
I had what where?

**Comment by milanmdev** [comment]
Not gonna let you know dummy
