### ISSUE TITLE
Still not this code

### ISSUE THREAD

**Issue by blaise69** [callbacc/Donut#2]

**Comment by blaise69** [comment]
UR A SNAKE!

**Comment by blaise69** [comment]
HISS HISS HISS HISS HISS HISS HISS HISS HISS

**Comment by callbacc** [comment]
Why do I need to show you proof of something I coded?

**Comment by 572512230701006851** [comment]
Because we want to check if you actually coded it, right now you have no evidence that it is actually yours. So you should show proof of what you coded.

**Comment by blaise69** [comment]
Yeah i agree with @callbacc u seem to only have the version 3 commit but we have the v1 v2 commits and every bug fix in between!

**Comment by callbacc** [comment]
Why should I show you proof of something that's only my page? Could you show me proof that you coded it?

**Comment by blaise69** [comment]
You want proof my guy?

**Comment by callbacc** [comment]
Yup.

**Comment by blaise69** [comment]
Got it captain just send me a screenshot of when you downloaded the code? form you vps that you gave me.... Also Proof that i coded it what did "you" use to gather playlists? What did you use for the database? Where is the discord application that is in 182 servers? Why does the support server in the readme point to the server @572512230701006851  is the owner of?
How would i know there is a custom version of lavalink so that it will work with eris?   and if you read in the package.json
![image](https://user-images.githubusercontent.com/62070631/90984754-0d7cac80-e545-11ea-9a8f-9e0e1a45feac.png)
that looks like @572512230701006851 private github project we post each and every update to 
So hiss ur way through these buddy

**Comment by blaise69** [comment]
Plus my @572512230701006851 and i's code is way to complex for you

**Comment by blaise69** [comment]
So @callbacc please prove to me it is ur code?

**Comment by callbacc** [comment]
Can you prove it that it's your code?

**Comment by 572512230701006851** [comment]
So you're asking for more proof, even though you didn't specify any proof that it is actually yours? That seems rather suspicious.

**Comment by blaise69** [comment]
Please read this message https://github.com/callbacc/Donut/issues/2#issuecomment-678802333

**Comment by blaise69** [comment]
So prove it for me please @callbacc

**Comment by callbacc** [comment]
I'm sorry but you're on my page and you're accusing me of stealing my code?

**Comment by blaise69** [comment]
No do i need to make my entire project public to show that ur attempting to steal my code and doing a bad job at it! Because its funny how your commit start a v3 and mine starts at v1

**Comment by callbacc** [comment]
I'm not sure I understood that.

**Comment by blaise69** [comment]
And you still dont not have proof that this is ur bot....

**Comment by callbacc** [comment]
You already see the proof. You're on my page.

**Comment by blaise69** [comment]
Okay buddy ur not going to win this

**Comment by blaise69** [comment]
Listen ill let you sit here and feel good about yourself, Again how many server does this code have? and why does the support server in the read me go to my bots support server and my bots invite link that is all i need to say about that pretty sad that you need to steal code to make yourself look good all because someone wont say sorry like i had nothing todo with it but you dragged me into it for NO REASON! Like i gave you a spot in my development team that now is no longer because of you! I legit dont understand what you need to gain out of this! Just an fyi ill be posting more in here to expose you buddy!

**Comment by callbacc** [comment]
Have a great day.

**Comment by blaise69** [comment]
![image](https://user-images.githubusercontent.com/62070631/90985148-060ad280-e548-11ea-9d58-2d7d9f58a878.png)
![image](https://user-images.githubusercontent.com/62070631/90985161-18850c00-e548-11ea-923f-f8d77d46a716.png)
![image](https://user-images.githubusercontent.com/62070631/90985175-20dd4700-e548-11ea-9dac-22e81e092799.png)
![image](https://user-images.githubusercontent.com/62070631/90985199-5f730180-e548-11ea-967e-1ff01b3b6542.png)
![image](https://user-images.githubusercontent.com/62070631/90985218-87626500-e548-11ea-94cb-b54377bf3822.png)

**Comment by blaise69** [comment]
You my good sir are exposed!
